
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-16
owner: ucsb-cs156-s25
repo_name: team01-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jeffreylin26-HelpRequest-create-controller","number":52,"title":"jl - create controller and implement get and post","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/52"},{"author":{"id":"U_kgDOCEZbAQ","is_bot":false,"login":"johnhagedorncs","name":"John Hagedorn"},"headRefName":"pc-create-db-table-commits","number":51,"title":"pc - create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/51"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"Wilson-Controller/Endpoints","number":49,"title":"WL - created RecommendationRequest controller, added GET/PUT/DELETE/POST methods ","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/49"}]
