
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-16
owner: ucsb-cs156-s25
repo_name: team01-s25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjYyNDA0OTIx","is_bot":false,"login":"applechristian","name":"Christian Lee"},"headRefName":"pc-delete-for-review-table","number":69,"title":"Cl delete for review table","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/69"},{"author":{"id":"MDQ6VXNlcjYyNDA0OTIx","is_bot":false,"login":"applechristian","name":"Christian Lee"},"headRefName":"cl-put-for-review-table","number":68,"title":"Cl put for review table","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/68"}]
