
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-16
owner: ucsb-cs156-s25
repo_name: team01-s25-16
pull_requests: [{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-put-endpoint","number":56,"title":"Dk menuitem put endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/56"},{"author":{"id":"MDQ6VXNlcjQ1ODkwOTMy","is_bot":false,"login":"jeffreylin26","name":"Jeffrey Lin"},"headRefName":"jeffreylin26-helprequests-get-by-id","number":55,"title":"jl helprequests get by id","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/55"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-menuitem-delete-endpoint","number":54,"title":"dk - updated menu items controller for DELETE","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/54"},{"author":{"id":"MDQ6VXNlcjc3MzEwNzE5","is_bot":false,"login":"Wilson730","name":"Wilson Lau"},"headRefName":"Wilson-Controller/Endpoints","number":49,"title":"WL - created RecommendationRequest controller, added GET/PUT/DELETE/POST methods ","url":"https://github.com/ucsb-cs156-s25/team01-s25-16/pull/49"}]
